<a href="https://colab.research.google.com/github/JASMINPATNAIK/DMDW-Lab/blob/main/18CSE181_Jasmin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=[int(i) for i in input().split()]
arr=np.array(arr)
arr

4 5 6 7 8


array([4, 5, 6, 7, 8])

In [ ]:
print(np.__version__)

1.18.5


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
#tuple to create array
arr=np.array((1,2,3,4))
arr

array([1, 2, 3, 4])

In [ ]:
#create a 0-D array
a=np.array(10)
a

array(10)

In [ ]:
#create a 1-D array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
#create a 2-D array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#create a 3-D array
arr= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#check number of dimensions
a=np.array(10)
b=np.array([1,2,3,4,5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('print 3 rd element of 1stdim', arr[0, 3])

print 3 rd element of 1stdim 4


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6
